name: guitar_book
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^4.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

# 👇 VERY IMPORTANT (this must be OUTSIDE "flutter:")
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
